---
- name: Add Debian testing repo
  apt_repository:
    repo: deb http://deb.debian.org/debian/ testing main

- name: Pin Debian testing repo
  copy:
    content: |
      Package: *
      Pin: release a=testing
      Pin-Priority: -1
    dest: /etc/apt/preferences.d/limit-testing

- name: Install WireGuard
  apt:
    update_cache: True
    name:
      - wireguard-dkms
    default_release: testing

- name: Create WireGuard config directory
  file:
    path: /etc/wireguard
    state: directory

- name: Instantiate WireGuard network devices
  template:
    src: wireguard.netdev.j2
    dest: /etc/systemd/network/wg{{ wg.key | int }}.netdev
    owner: systemd-network
    mode: 0640
  loop: "{{ wireguard_interfaces | dict2items }}"
  loop_control:
    loop_var: wg
  notify:
    - Reload systemd configuration
    - Restart systemd-networkd

- name: Instantiate WireGuard network
  template:
    src: wireguard.network.j2
    dest: /etc/systemd/network/wg{{ wg.key | int }}.network
    owner: systemd-network
  loop: "{{ wireguard_interfaces | dict2items }}"
  loop_control:
    loop_var: wg
  notify:
    - Reload systemd configuration
    - Restart systemd-networkd
