---
- name: Reload systemd configuration
  service:
    daemon_reload: True

- name: Restart systemd-networkd
  service:
    name: systemd-networkd
    enabled: yes
    state: restarted

# - name: Run WireGuard service instances
#   service:
#     name: wireguard@wg{{ wg.key | int }}
#     enabled: yes
#     state: restarted
#   loop: "{{ wireguard_interfaces | dict2items }}"
#   loop_control:
#     loop_var: wg